data-prepper:
  # Tells the data-prepper sub-chart to use an existing ConfigMap
  # for its pipeline configurations.
  pipelineConfig:
    demoPipeline: ""
    enabled: true
    config:
        # Main Data Prepper configuration file content
        # This content will be mounted as pipelines.yaml in the ConfigMap
        entry-pipeline:
          delay: "100"
          source:
            otel_trace_source:
              ssl: false
              authentication:
                unauthenticated: {}
          buffer:
            bounded_blocking:
              buffer_size: 10240
              batch_size: 160
          sink:
            - pipeline:
                name: "raw-trace-pipeline"
            - pipeline:
                name: "service-map-pipeline"

        raw-trace-pipeline:
          delay: "100"
          source:
            pipeline:
              name: "entry-pipeline"
          buffer:
            bounded_blocking:
              buffer_size: 10240
              batch_size: 160
          processor:
            - otel_traces: {}
          sink:
            - opensearch:
                hosts: ["https://opensearch.opensearch.svc.cluster.local:9200"]
                insecure: true
                username: "admin"
                password: "admin"
                index_type: trace-analytics-raw
            - stdout: {}

        service-map-pipeline:
          source:
            pipeline:
              name: "entry-pipeline"
          buffer:
            bounded_blocking:
              buffer_size: 10240
              batch_size: 160
          processor:
            - service_map: {}
          sink:
            - opensearch:
                hosts: ["https://opensearch.opensearch.svc.cluster.local:9200"]
                # The insecure option is used here for simplicity, but in production,
                insecure: true
                username: "admin"
                password: "admin"
                index_type: trace-analytics-service-map
            - stdout: {}

        logs-pipeline:
          workers: 1
          delay: "100"
          source:
            otel_logs_source:
              # This source listens for OTLP log data.
              # It shares the OTLP server with otel_trace_source, typically on port 21890 (gRPC) / 21891 (HTTP) when ssl is false.
              # Your OTel Collector is configured to send logs to port 21890.
              port: 21892
              ssl: false
              authentication:
                unauthenticated: {} # Matches OTel collector exporter which sends unauthenticated requests
          buffer:
            bounded_blocking:
              buffer_size: 512 # Maximum number of records the buffer can hold
              batch_size: 64    # Number of records to send to the sink in a single batch
          sink:
            - opensearch:
                hosts: ["http://opensearch-masters.opensearch.svc.cluster.local:9200"]
                insecure: true # Set to false if OpenSearch uses TLS and you configure Data Prepper's sink for TLS
                index_type: custom
                bulk_size: 10
                index: "otel-logs-%{yyyy.MM.dd}" # Dynamic index name based on date, e.g., otel-logs-2023.10.27
                username: "admin"
                password: "admin"
              # Optional: Define an OpenSearch index template for better control over mappings and settings for your log indices.
              # template_file: "/usr/share/data-prepper/pipelines/opensearch_log_template.json"
              # document_id_field: "traceId" # If you want to use a field from the log as the document ID
              # routing_field: "service.name" # If you want to route documents to specific shards based on a field



opentelemetry-collector:
  mode: deployment

  presets:
    logsCollection:
      enabled: true
      includeCollectorLogs: true
  
  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.127.0"
  
  config:
    receivers:
        otlp:
            protocols:
              http: 
                cors:
                  allowed_origins:
                    - "*"
              grpc: {} 
        zipkin: {}

    processors:
        batch/traces:
            timeout: 1s
            send_batch_size: 50
        batch/logs:
            timeout: 1s
            send_batch_size: 100

    exporters:
        debug: 
          verbosity: detailed
        otlp/data-prepper:
            endpoint: otel-data-prepper.opensearch.svc.cluster.local:21890
            tls:
              insecure: true
              insecure_skip_verify: true
        otlp/data-prepper-logs:
          endpoint: otel-data-prepper.opensearch.svc.cluster.local:21892
          tls:
            insecure: true
            insecure_skip_verify: true
              
    service:
        pipelines:
            traces:
              receivers: [otlp, zipkin]
              processors: [batch/traces]
              exporters: [debug,otlp/data-prepper]
            metrics: null
            logs:
              receivers: [otlp]
              processors: [batch/logs]
              exporters: [otlp/data-prepper-logs]
