data-prepper:
  # Tells the data-prepper sub-chart to use an existing ConfigMap
  # for its pipeline configurations.
  pipelineConfig:
    demoPipeline: ""
    enabled: true
    config:
        # Main Data Prepper configuration file content
        # This content will be mounted as pipelines.yaml in the ConfigMap
        entry-pipeline:
          delay: "100"
          source:
            otel_trace_source:
              ssl: false
              authentication:
                unauthenticated: {}
          buffer:
            bounded_blocking:
              buffer_size: 10240
              batch_size: 160
          sink:
            - pipeline:
                name: "raw-trace-pipeline"
            - pipeline:
                name: "service-map-pipeline"

        raw-trace-pipeline:
          delay: "100"
          source:
            pipeline:
              name: "entry-pipeline"
          buffer:
            bounded_blocking:
              buffer_size: 10240
              batch_size: 160
          processor:
            - otel_traces: {}
          sink:
            - opensearch:
                hosts: ["https://opensearch.opensearch.svc.cluster.local:9200"]
                insecure: true
                username: "admin"
                password: "admin"
                index_type: trace-analytics-raw
            - stdout: {}

        service-map-pipeline:
          source:
            pipeline:
              name: "entry-pipeline"
          buffer:
            bounded_blocking:
              buffer_size: 10240
              batch_size: 160
          processor:
            - service_map: {}
          sink:
            - opensearch:
                hosts: ["https://opensearch.opensearch.svc.cluster.local:9200"]
                # The insecure option is used here for simplicity, but in production,
                insecure: true
                username: "admin"
                password: "admin"
                index_type: trace-analytics-service-map
            - stdout: {}

opentelemetry-collector:
  mode: deployment
  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.127.0"
  
  config:
    receivers:
        otlp:
            protocols:
              http: 
                cors:
                  allowed_origins:
                    - "*"
              grpc: {} 
        zipkin: {}

    processors:
        batch/traces:
            timeout: 1s
            send_batch_size: 50

    exporters:
        debug: 
          verbosity: detailed
        otlp/data-prepper:
            endpoint: otel-data-prepper.opensearch.svc.cluster.local:21890
            tls:
              insecure: true
              insecure_skip_verify: true

    service:
        pipelines:
            traces:
              receivers: [otlp, zipkin]
              processors: [batch/traces]
              exporters: [debug,otlp/data-prepper]
            metrics: null
            logs: null
